#################################################################
# Custom sensors that can only have 1 of 2 values.
# https://www.home-assistant.io/integrations/binary_sensor/
#################################################################

# Wan Monitor
- platform: ping
  host: 8.8.8.8
  name: WAN
  scan_interval: 60

# Night sensor
- platform: tod
  name: Night
  after: sunset
  after_offset: "-01:00"
  before: sunrise
  before_offset: "-01:00"

# Day sensor
- platform: tod
  name: Day
  after: sunrise
  after_offset: "-01:00"
  before: sunset
  before_offset: "-01:00"

# Holiday sensors
# Useful for holiday "seasons" that can extend more than 1 day
- platform: template
  sensors:
    thanksgiving:
      unique_id: binary_sensor.halloween
      friendly_name: Halloween
      value_template: >
          {%- set today = now() %}
          {%- set halloween_start = now().replace(month=10,day=15) %}
          {%- set halloween_end = now().replace(month=10,day=31) %}
          {{ today >= halloween_start or today <= halloween_end }}
