#################################################################
# Use this to customize all entities in a domain
# https://www.home-assistant.io/docs/configuration/customizing-devices/
#################################################################
