#################################################################
# Groups combine multiple entities into a single entity
# https://www.home-assistant.io/integrations/group/
#################################################################
