#################################################################
# Scenes capture the states you want certain entities to be
# https://www.home-assistant.io/integrations/scene/
#################################################################
