#################################################################
# Sensors monitor the states and conditions of a variety of entities
# https://www.home-assistant.io/integrations/sensor
#################################################################

# Server

- platform: systemmonitor
  resources:
    - type: processor_use
    - type: memory_use_percent
    - type: last_boot
    - type: disk_use_percent
